src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/IntSetting.kt
src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.kt
src/android/app/src/main/jni/config.cpp
src/android/app/src/main/jni/default_ini.h
src/android/app/src/main/jni/native.cpp
src/android/app/src/main/res/values-es/strings.xml
src/android/app/src/main/res/values/strings.xml
src/audio_core/hle/hle.cpp
src/citra/config.cpp
src/citra/default_ini.h
src/citra_qt/configuration/config.cpp
src/citra_qt/configuration/configure_audio.cpp
src/citra_qt/configuration/configure_audio.h
src/citra_qt/configuration/configure_audio.ui
src/common/settings.cpp
src/common/settings.h
src/core/core.cpp
src/core/core.h
src/core/perf_stats.cpp
src/core/perf_stats.h

Ported from Lime3DS and Citra Enhanced.

Hack: Implement Realtime Audio Playback Option

---

src/citra_qt/CMakeLists.txt
src/citra_qt/infrared/skylanderportal/skylander_dialog.cpp
src/citra_qt/infrared/skylanderportal/skylander_dialog.h
src/citra_qt/main.cpp
src/citra_qt/main.h
src/citra_qt/main.ui
src/common/common_paths.h
src/core/CMakeLists.txt
src/core/hle/service/ir/ir_portal.cpp
src/core/hle/service/ir/ir_portal.h
src/core/hle/service/ir/ir_user.cpp
src/core/hle/service/ir/ir_user.h
src/video_core/renderer_opengl/gl_resource_manager.h

Support for [Skylanders Portal emulation](https://www.reddit.com/r/skylanders/comments/1cu8bsa/emulated_3ds_portal_on_citra/) by [deReeperJosh](https://github.com/deReeperJosh/citra). Still a work in progress, it doesn't work with every Skylander game yet. For now, Portal is recognized in Giants, Swap Force and Superchargers Racing, but it doesn't work with Spyro's Adventure or Trap Team. He's got a demo of it in action on [YouTube](https://www.youtube.com/watch?v=bY1YzG_ckQE) as well. You can access the Skylanders Manager through the Tools menu.

IR User: Emulate Infrared Skylander Portal

---

.gitmodules
externals/CMakeLists.txt
src/android/app/src/main/java/org/citra/citra_emu/fragments/LicensesFragment.kt
src/android/app/src/main/res/values-es/strings.xml
src/android/app/src/main/res/values/arrays.xml
src/android/app/src/main/res/values/licenses.xml
src/android/app/src/main/res/values/strings.xml
src/audio_core/CMakeLists.txt
src/audio_core/oboe_sink.cpp
src/audio_core/oboe_sink.h
src/audio_core/sink_details.cpp
src/audio_core/sink_details.h

Android: Implement Oboe audio backend

---

.ci/android.sh
.ci/source.sh
src/android/app/build.gradle.kts
src/android/app/src/main/res/values/strings.xml
src/citra/citra.cpp
src/citra_qt/configuration/configure_system.cpp
src/citra_qt/game_list.cpp
src/citra_qt/game_list.h
src/citra_qt/main.cpp
src/citra_qt/main.h

citra_qt: Cleanup UI (Part 3)

---

src/citra_qt/configuration/configure_audio.ui
src/citra_qt/configuration/configure_camera.ui
src/citra_qt/configuration/configure_debug.ui
src/citra_qt/configuration/configure_enhancements.ui
src/citra_qt/configuration/configure_general.ui
src/citra_qt/configuration/configure_graphics.ui
src/citra_qt/configuration/configure_layout.ui
src/citra_qt/configuration/configure_system.ui
src/citra_qt/configuration/configure_ui.ui

Mostly copyedit changes and section reorganization.

citra_qt: Cleanup UI (Part 4)

---

.github/workflows/build.yml
.github/workflows/format.yml
.github/workflows/update-actions.yml

* **[lukka/get-cmake](https://github.com/lukka/get-cmake)** published a new release **[v3.30.3](https://github.com/lukka/get-cmake/releases/tag/v3.30.3)** on 2024-08-30T10:10:04Z
* **[ilammy/msvc-dev-cmd](https://github.com/ilammy/msvc-dev-cmd)** published a new release **[v1.13.0](https://github.com/ilammy/msvc-dev-cmd/releases/tag/v1.13.0)** on 2024-01-01T04:32:14Z
* **[tecolicom/actions-use-homebrew-tools](https://github.com/tecolicom/actions-use-homebrew-tools)** published a new release **[v1.3](https://github.com/tecolicom/actions-use-homebrew-tools/releases/tag/v1.3)** on 2024-08-19T10:08:39Z
* **[actions/cache](https://github.com/actions/cache)** published a new release **[v4.0.2](https://github.com/actions/cache/releases/tag/v4.0.2)** on 2024-03-19T15:55:41Z
* …

Update GitHub Action Versions

---

dist/citra-qt.6
dist/citra.6
src/citra/citra.cpp
src/citra_qt/CMakeLists.txt
src/citra_qt/main.cpp
src/citra_qt/main.h
src/common/CMakeLists.txt
src/common/win_console.h

Partially ported from Lime3DS, although taken in a different direction.

citra_qt: Improve parity of command line options with SDL frontend

---

src/android/app/src/main/java/io/github/borked3ds/android/features/settings/ui/SettingsAdapter.kt

Caused a crash when pulling up a menu option.

SettingsAdapter.kt: Revert setting locale with string.format

---

src/android/app/src/main/java/io/github/borked3ds/android/fragments/EmulationFragment.kt

Rather than try to switch between Portrait and Landscape modes, tapping the button will now rotate the screen 1/4 clockwise from whatever the starting orientation is.

Android: Refactor Rotate Screen button

---

src/android/app/src/main/res/layout/list_item_settings_header.xml

fixes the Little broken ui in settings

Android: list_item_settings_header: fix spacing

---

src/android/app/src/main/java/io/github/borked3ds/android/features/settings/model/BooleanSetting.kt
src/android/app/src/main/java/io/github/borked3ds/android/features/settings/model/IntSetting.kt
src/android/app/src/main/java/io/github/borked3ds/android/features/settings/model/Settings.kt
src/android/app/src/main/java/io/github/borked3ds/android/features/settings/ui/SettingsFragmentPresenter.kt
src/android/app/src/main/java/io/github/borked3ds/android/fragments/EmulationFragment.kt
src/android/app/src/main/java/io/github/borked3ds/android/ui/main/MainActivity.kt
src/android/app/src/main/java/io/github/borked3ds/android/utils/EmulationMenuSettings.kt
src/android/app/src/main/jni/default_ini.h
src/android/app/src/main/res/drawable/ic_frames.xml
src/android/app/src/main/res/layout/fragment_emulation.xml
src/android/app/src/main/res/menu/menu_overlay_options.xml
src/android/app/src/main/res/values-night/borked3ds_colors.xml
src/android/app/src/main/res/values/arrays.xml
src/android/app/src/main/res/values/borked3ds_colors.xml
src/android/app/src/main/res/values/strings.xml

Add ability to choose position and to toggle display of fps, speed, ram usage, and battery temperature.

Android: Add Performance Stats Overlay settings UI

---

src/video_core/rasterizer_accelerated.cpp
src/video_core/rasterizer_accelerated.h
src/video_core/renderer_opengl/pica_to_gl.h
src/video_core/renderer_vulkan/pica_to_vk.h

SIMD optimizations for:
* ColorRGBA8 conversion
* LightColor conversion
Also: Use proper preprocessor macro names

video_core: More SIMD optimizations

---

.ci/ios.sh
.ci/macos.sh
CMakeModules/DownloadExternals.cmake

MacOS: Fix external MoltenVK bundling

---

src/android/app/src/main/java/io/github/borked3ds/android/overlay/InputOverlay.kt

Unintentionally resulted in D-pad and Joystick becoming uneditable.
Addresses #335

InputOverlay.kt: Revert null safety checks

---

src/android/app/src/main/java/io/github/borked3ds/android/fragments/EmulationFragment.kt

EmulationFragment.kt: Restore game icon loader

---

.ci/android.sh
CMakeLists.txt
src/android/app/build.gradle.kts
src/android/app/src/main/java/io/github/borked3ds/android/overlay/InputOverlay.kt
src/audio_core/time_stretch.cpp
src/borked3ds/emu_window/emu_window_sdl2.cpp
src/common/cityhash.cpp
src/common/cityhash.h
src/common/vector_math.h
src/core/frontend/framebuffer_layout.cpp
src/core/gdbstub/hio.cpp
src/core/hle/service/hid/hid.cpp
src/input_common/motion_emu.cpp
src/video_core/host_shaders/texture_filtering/bicubic.frag
src/video_core/host_shaders/texture_filtering/scale_force.frag
src/video_core/rasterizer_cache/rasterizer_cache.h
src/video_core/renderer_opengl/gl_stream_buffer.cpp
src/video_core/renderer_software/sw_clipper.cpp
src/video_core/renderer_software/sw_lighting.cpp
src/video_core/renderer_software/sw_proctex.cpp
src/video_core/renderer_software/sw_rasterizer.cpp
src/video_core/shader/generator/glsl_fs_shader_gen.cpp
src/video_core/texture/etc1.cpp

* Fix some NEON instructions
* Introduce more AVX instructions
* Update SIMD compiler flags

Optimize SIMD vector math instructions

---

src/common/vector_math.h

Fixes NEON build errors on Pi-based devices when using GCC 12.
Addresses #330

vector_math.h: Avoid strict aliasing violations and use safer memory operations

---

src/video_core/renderer_vulkan/vk_render_manager.cpp
src/video_core/renderer_vulkan/vk_render_manager.h
src/video_core/renderer_vulkan/vk_texture_runtime.cpp

Slightly improve logging and validation.

Some minor Vulkan updates

---

src/borked3ds_qt/configuration/configure_input.cpp

Fixes issue where Circle Pad and C-Stick Up/Down button mappings are reversed when configured with the "Set Analog Stick" button.
Fixes #358

configure_input.cpp: Convert SDL Axes to button mappings

---

src/android/app/src/main/java/io/github/borked3ds/android/adapters/GameAdapter.kt
src/android/app/src/main/java/io/github/borked3ds/android/fragments/GamesFragment.kt
src/android/app/src/main/java/io/github/borked3ds/android/fragments/SearchFragment.kt
src/android/app/src/main/res/drawable/shortcut_edit_background.xml
src/android/app/src/main/res/layout/dialog_shortcut.xml
src/android/app/src/main/res/values/strings.xml

Adds ability to customize game shortcuts with:
- Custom name input
- Editable icon via image picker
- Ability to stretch to fit or zoom to fit the shortcut icon

Android: Enhance shortcut customization with a custom dialog
